//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationRecordTable
    {
        public int Application_record_ID { get; set; }
        public int Recruitment_status { get; set; }
        public int MemberID { get; set; }
        public int ProjectID { get; set; }
        public int Application_status_number { get; set; }
        public string Application_record { get; set; }
    
        public virtual ApplicationStatusTable ApplicationStatusTable { get; set; }
        public virtual MemberTable MemberTable { get; set; }
        public virtual MemberTable MemberTable1 { get; set; }
        public virtual ProjectTable ProjectTable { get; set; }
    }
}
