//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAllTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassAllTable()
        {
            this.DealClassTables = new HashSet<DealClassTable>();
        }
    
        public int ClassID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ClassName { get; set; }
        public string ClassDescription { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public byte[] ClassPicture { get; set; }
        public Nullable<int> SiteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealClassTable> DealClassTables { get; set; }
        public virtual MemberTable MemberTable { get; set; }
    }
}
