//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealClassTable
    {
        public int DealClassID { get; set; }
        public int ClassID { get; set; }
        public int CouponID { get; set; }
        public int MemberID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ClassAllTable ClassAllTable { get; set; }
        public virtual CouponTable CouponTable { get; set; }
        public virtual MemberTable MemberTable { get; set; }
    }
}
