//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mdgroup1Entities : DbContext
    {
        public mdgroup1Entities()
            : base("name=mdgroup1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdministratorPermissionTable> AdministratorPermissionTables { get; set; }
        public virtual DbSet<ApplicationRecordTable> ApplicationRecordTables { get; set; }
        public virtual DbSet<ApplicationStatusTable> ApplicationStatusTables { get; set; }
        public virtual DbSet<CityTable> CityTables { get; set; }
        public virtual DbSet<ClassAllTable> ClassAllTables { get; set; }
        public virtual DbSet<CouponTable> CouponTables { get; set; }
        public virtual DbSet<DealClassTable> DealClassTables { get; set; }
        public virtual DbSet<DealProjectTable> DealProjectTables { get; set; }
        public virtual DbSet<DealSiteLoanTable> DealSiteLoanTables { get; set; }
        public virtual DbSet<EvaluateAllTable> EvaluateAllTables { get; set; }
        public virtual DbSet<MemberCouponTable> MemberCouponTables { get; set; }
        public virtual DbSet<MemberProductRelateAllTable> MemberProductRelateAllTables { get; set; }
        public virtual DbSet<MemberRelationshipAllTable> MemberRelationshipAllTables { get; set; }
        public virtual DbSet<MemberSiteAllTable> MemberSiteAllTables { get; set; }
        public virtual DbSet<MemberSkillDetailTable> MemberSkillDetailTables { get; set; }
        public virtual DbSet<MemberTable> MemberTables { get; set; }
        public virtual DbSet<MusicarticlePic> MusicarticlePics { get; set; }
        public virtual DbSet<MusicarticleTable> MusicarticleTables { get; set; }
        public virtual DbSet<ProductTable> ProductTables { get; set; }
        public virtual DbSet<ProjectSkillAllTable> ProjectSkillAllTables { get; set; }
        public virtual DbSet<ProjectStatusAllTable> ProjectStatusAllTables { get; set; }
        public virtual DbSet<ProjectTable> ProjectTables { get; set; }
        public virtual DbSet<SitePeriodTable> SitePeriodTables { get; set; }
        public virtual DbSet<SitePicTable> SitePicTables { get; set; }
        public virtual DbSet<SiteTable> SiteTables { get; set; }
        public virtual DbSet<SkillCategoryAllTable> SkillCategoryAllTables { get; set; }
        public virtual DbSet<SkillDetailTable> SkillDetailTables { get; set; }
        public virtual DbSet<SocialRelationTable> SocialRelationTables { get; set; }
        public virtual DbSet<StyleAllTable> StyleAllTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
