//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTable()
        {
            this.EvaluateAllTables = new HashSet<EvaluateAllTable>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> StyleID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public byte[] Photo { get; set; }
        public string ProductMediaFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluateAllTable> EvaluateAllTables { get; set; }
        public virtual MemberTable MemberTable { get; set; }
        public virtual StyleAllTable StyleAllTable { get; set; }
    }
}
