//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTable()
        {
            this.ApplicationRecordTables = new HashSet<ApplicationRecordTable>();
            this.DealProjectTables = new HashSet<DealProjectTable>();
            this.ProjectSkillAllTables = new HashSet<ProjectSkillAllTable>();
        }
    
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> ProductionPeriod { get; set; }
        public string Budget { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> ReleaseMemberNumber { get; set; }
        public byte[] ProjectPicture { get; set; }
        public Nullable<int> ProjectStatus { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string ProjectName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationRecordTable> ApplicationRecordTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealProjectTable> DealProjectTables { get; set; }
        public virtual MemberTable MemberTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSkillAllTable> ProjectSkillAllTables { get; set; }
        public virtual ProjectStatusAllTable ProjectStatusAllTable { get; set; }
    }
}
