//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitePeriodTable
    {
        public int SiteID { get; set; }
        public int SitePeriodID { get; set; }
        public Nullable<bool> MonMorning { get; set; }
        public Nullable<bool> MonAfternoon { get; set; }
        public Nullable<bool> MonNight { get; set; }
        public Nullable<bool> MonMidnight { get; set; }
        public Nullable<bool> TuesMorning { get; set; }
        public Nullable<bool> TuesAfternoon { get; set; }
        public Nullable<bool> TuesNight { get; set; }
        public Nullable<bool> TuesMidnight { get; set; }
        public Nullable<bool> WedMorning { get; set; }
        public Nullable<bool> WedAfternoon { get; set; }
        public Nullable<bool> WedNight { get; set; }
        public Nullable<bool> WedMidnight { get; set; }
        public Nullable<bool> ThurMorning { get; set; }
        public Nullable<bool> ThurAfternoon { get; set; }
        public Nullable<bool> ThurNight { get; set; }
        public Nullable<bool> ThurMidnight { get; set; }
        public Nullable<bool> FriMorning { get; set; }
        public Nullable<bool> FriAfternoon { get; set; }
        public Nullable<bool> FriNight { get; set; }
        public Nullable<bool> FriMidnight { get; set; }
        public Nullable<bool> SatMorning { get; set; }
        public Nullable<bool> SatAfternoon { get; set; }
        public Nullable<bool> SatNight { get; set; }
        public Nullable<bool> SatMidnight { get; set; }
        public Nullable<bool> SunMorning { get; set; }
        public Nullable<bool> SunAfternoon { get; set; }
        public Nullable<bool> SunNight { get; set; }
        public Nullable<bool> SunMidnight { get; set; }
    
        public virtual SiteTable SiteTable { get; set; }
    }
}
