//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillDetailTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkillDetailTable()
        {
            this.MemberSkillDetailTables = new HashSet<MemberSkillDetailTable>();
            this.ProjectSkillAllTables = new HashSet<ProjectSkillAllTable>();
        }
    
        public int SkillID { get; set; }
        public string SkillDescription { get; set; }
        public Nullable<int> SkillCategoryID { get; set; }
        public byte[] SkillDetailPicture { get; set; }
        public string SkillName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSkillDetailTable> MemberSkillDetailTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSkillAllTable> ProjectSkillAllTables { get; set; }
        public virtual SkillCategoryAllTable SkillCategoryAllTable { get; set; }
    }
}
